[[main]]
  identifier = "more"
  name = "百宝箱"
  pre = '<i class="fas fa-tools"></i>'
  weight = 1

[[main]]
  parent = "more"
  name = "图谱"
  pre = '<i class="fas fa-atlas"></i>'
  url = "https://www.processon.com/view/link/5ac64532e4b00dc8a02f05eb"
  weight = 1

#[[main]]
#  parent = "more"
#  name = "谷歌加速"
#  pre = '<i class="fab fa-google"></i>'
#  url = "https://google.icloudnative.io"
#  weight = 2

#[[main]]
#  parent = "more"
#  name = "网盘资源"
#  pre = '<i class="fab fa-google-drive"></i>'
#  url = "https://www.aliyundrive.com/s/1SpRnYKBZDA"
#  weight = 3

#[[main]]
#  parent = "more"
#  name = "监控"
#  pre = '<i class="fas fa-heartbeat"></i>'
#  url = "uptime-status/"
#  weight = 4

[[main]]
  parent = "more"
  name = "导航"
  pre = '<i class="fas fa-map-marked-alt"></i>'
  url = "https://nav.ryanyang.workers.dev/"
  weight = 5

#[[main]]
#  parent = "more"
#  name = "共享文本"
#  pre = '<i class="fas fa-paste"></i>'
#  url = "https://privatebin.icloudnative.io/"
#  weight = 6

#[[main]]
#  identifier = "umami"
#  name = "实时访客"
#  pre = '<i class="fas fa-chart-line"></i>'
#  url = "https://umami.icloudnative.io/share/UuDHNJJWIShegM2N/%E4%BA%91%E5%8E%9F%E7%94%9F%E5%AE%9E%E9%AA%8C%E5%AE%A4?theme=dark"
#  weight = 2

[[main]]
  identifier = "rss"
  name = "RSS"
  pre = '<svg class="svg-inline--fa fa-rss-square fa-w-12 fa-fw" style="width: 1.05em; margin: -0.02em .2em 0;" aria-hidden="true" data-prefix="fas" data-icon="rss-square" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg=""><path fill="currentColor" d="M400 32H48C21.49 32 0 53.49 0 80v352c0 26.51 21.49 48 48 48h352c26.51 0 48-21.49 48-48V80c0-26.51-21.49-48-48-48zM112 416c-26.51 0-48-21.49-48-48s21.49-48 48-48 48 21.49 48 48-21.49 48-48 48zm157.533 0h-34.335c-6.011 0-11.051-4.636-11.442-10.634-5.214-80.05-69.243-143.92-149.123-149.123-5.997-.39-10.633-5.431-10.633-11.441v-34.335c0-6.535 5.468-11.777 11.994-11.425 110.546 5.974 198.997 94.536 204.964 204.964.352 6.526-4.89 11.994-11.425 11.994zm103.027 0h-34.334c-6.161 0-11.175-4.882-11.427-11.038-5.598-136.535-115.204-246.161-251.76-251.76C68.882 152.949 64 147.935 64 141.774V107.44c0-6.454 5.338-11.664 11.787-11.432 167.83 6.025 302.21 141.191 308.205 308.205.232 6.449-4.978 11.787-11.432 11.787z"></path></svg>'
  url = "index.xml"
  weight = 3

[[main]]
  identifier = "about"
  name = "关于"
  pre = '<i class="fas fa-user-graduate"></i>'
  url = "about/"
  weight = 5

[[main]]
  identifier = "friends"
  name = "友链"
  pre = '<i class="fas fa-user-friends"></i>'
  url = "friends/"
  weight = 7

[[main]]
  identifier = "archive"
  name = "归档"
  pre = '<i class="fas fa-archive"></i>'
  url = "archive/"
  weight = 9

#[[main]]
#  identifier = "posts"
#  name = "博客"
#  pre = '<i class="fab fa-docker"></i>'
#  url = "posts/"
#  weight = 11

[[main]]
  identifier = "showcase"
  name = "项目"
  pre = '<i class="fab fa-github"></i>'
  url = "showcase/"
  weight = 13

[[main]]
  identifier = "books"
  name = "电子书"
  pre = '<i class="fas fa-book"></i>'
  weight = 15

#[[main]]
#  parent = "books"
#  name = "Envoy 中文指南"
#  url = "https://github.com/yangchuansheng/envoy-handbook"
#  weight = 1

[[main]]
  parent = "books"
  name = "Prometheus 中文文档"
  url = "prometheus/"
  weight = 2

[[main]]
  parent = "books"
  name = "Go 入门指南"
  url = "the-way-to-go/"
  weight = 3

[[main]]
  parent = "books"
  name = "天才源自刻意练习"
  url = "talent-is-overrated/"
  weight = 5
