# 生成网站根目录的地址
baseURL = "https://luoxding.github.io/"

# 主题
theme = "hugo-theme-walden"
#publishDir = "./docs"

# 列表分页基数
paginate = 12

# 多语言设置
defaultContentLanguage = "zh"

# [language]
#    [languages.en]
#        title = "Walden"
#        languageName = "English"
#        languageCode = "en-US"
#        weight = 1

#        # 用户参数
#        [languages.en.author]
#            name = "Homecat"
#            avatar = "images/default/avatar.jpg"
#            description = "Hi, I am Homecat, a Shaoxing native living in Shanghai. Reading, hiking, and coding are my hobbies. I have set my blog on Github to record interesting things and share with my friends."
#            email = "13050082@qq.com"

    [languages.zh]
        title = "老罗博客"
        languageName = "中文"
        languageCode = "zh-Hans-CN"
        weight = 2

        [languages.zh.author]
            name = "布衣老罗"
            avatar = "images/default/avatar.jpg"
            description = "维持生命真正需要的只有三样东西：空气、水和食物，除此之外的任何“必需品”都是不同程度地被包装出来的，人越活越复杂，自然也越活越累。"
            email = "412947296@qq.com"

# 主菜单

[languages.zh.menus]
    [[languages.zh.menus.main]]
        identifier = "home"
        name = "首页"
        url = "/"
        weight = 10
    [[languages.zh.menus.main]]
        identifier = "blog"
        name = "博客"
        url = "/blog/"
        weight = 20
    [[languages.zh.menus.main]]
        identifier = "note"
        name = "笔记"
        url = "/note/"
        weight = 30
    [[languages.zh.menus.main]]
        identifier = "categories"
        name = "分类"
        url = "/categories/"
        weight = 40
    [[languages.zh.menus.main]]
        identifier = "tags"
        name = "标签"
        url = "/tags/"
        weight = 50
    [[languages.zh.menus.main]]
        identifier = "archives"
        name = "归档"
        url = "/archives/"
        weight = 60

[params]
    headline = "/images/default/headline.jpg"
    thumbnail = "/images/default/thumbnail.jpg"
    
# 用于渲染的参数
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.parser]
            attribute = true
            autoHeadingID = true
            autoHeadingIDType = "github"
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = true
            xHTML = false
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = false
        noClasses = true
        style = "monokai"
        tabWidth = 4
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
        startLevel = 2


# 用于 Hugo theme 发布的参数
[module]
  [module.hugoVersion]
    extended = true
    min = "0.101.0"




